### ISSUE TITLE
Cannot connect to Edge Impulse Daemon

### ISSUE THREAD

**Issue by ShawnHymel** [edgeimpulse/firmware-nordic-thingy91#1] opened 2022-08-16 16:57 UTC
From user: https://forum.edgeimpulse.com/t/thingy-91-edge-impulse-not-working/5216

![image](https://user-images.githubusercontent.com/5232145/184935535-8da0f57d-2ecf-419b-9c19-139cbc76e10f.png)

I have replicated the error. I uploaded the latest firmware (firmware.hex) from https://docs.edgeimpulse.com/docs/development-platforms/officially-supported-mcu-targets/nordic-semi-thingy91. I'm unsure of the version, as there's no versioning on the files, but I downloaded the .zip on Aug 16, 2022. I could not get the Thingy to talk to the daemon, regardless of which UART port I picked. 

I tried flashing connectivity-bridge.hex to the nRF52840, and this did not solve the issue.

Before updating to the latest nRF Connect and flashing the newest firmware, I was able to connect the Thingy:91 to the edge-impulse-daemon without a problem.

OS: Windows 10 x64
nRF Connect for Desktop v3.11.1
nRF Programmer v2.3.3

**Comment by VojislavM** [comment] 2022-08-17 09:29
hey, I was doing some stuff with Nordic boards, experienced similar issue with Nordic nRF9160dk and nrf5340dk. I would assume they share the same issue. 
I will try looking into this by the end of this week and will keep you posted. 
I did try with Mac M1, but that should not make a difference, will try with my Linux laptop as well

**Comment by automatiek** [comment] 2022-08-24 18:16
@VojislavM what's the status on this issue?

**Comment by VojislavM** [comment] 2022-08-25 10:36
still on it. will let you know by tomorrow what are the findings.

**Comment by SwooshMihu** [comment] 2022-08-29 11:15
@VojislavM Hey! Any update on this issue? Thanks

**Comment by VojislavM** [comment] 2022-08-29 11:22
working on it will let you know soon!

**Comment by VojislavM** [comment] 2022-08-29 13:04
For now I can tell you that I am seeing the same thing. I was not able to communicate on both ports. 
```
❯ edge-impulse-daemon        
Edge Impulse serial daemon v1.15.1
Endpoints:
    Websocket: wss://remote-mgmt.edgeimpulse.com
    API:       https://studio.edgeimpulse.com/v1
    Ingestion: https://ingestion.edgeimpulse.com/

? Which device do you want to connect to? /dev/tty.usbmodem1101 (Nordic Semiconductor)
[SER] Connecting to /dev/tty.usbmodem1101
[SER] Serial is connected, trying to read config...

[SER] Failed to get info off device Timeout when waiting for >  (timeout: 5000) onConnected

❯ edge-impulse-daemon
Edge Impulse serial daemon v1.15.1
Endpoints:
    Websocket: wss://remote-mgmt.edgeimpulse.com
    API:       https://studio.edgeimpulse.com/v1
    Ingestion: https://ingestion.edgeimpulse.com/

? Which device do you want to connect to? /dev/tty.usbmodem1104 (Nordic Semiconductor)
[SER] Connecting to /dev/tty.usbmodem1104
[SER] Serial is connected, trying to read config...
[SER] Failed to get info off device Timeout when waiting for >  (timeout: 5000) onConnected
```
working on debugging this.

**Comment by VojislavM** [comment] 2022-08-29 19:29
the issue seems to be with connectivity bridge firmware. I need to test a bit more on multiple Thingy91 versions and will send the correct binary tomorrow.

**Comment by VojislavM** [comment] 2022-08-30 12:16
so, it comes down to connectivity bridge. 
You can try out to flash [connectivity bridge firmware](https://drive.google.com/file/d/1mUrRwm67GrxhlwomJ8h2pWxjqCG4J-TA/view?usp=sharing) 
and in combination with our [latest firmware](https://cdn.edgeimpulse.com/firmware/nordic-thingy91.zip) from documentation it should work. 
Also check out the Thingy:91 hardware version section in our documentation: https://docs.edgeimpulse.com/docs/development-platforms/officially-supported-mcu-targets/nordic-semi-thingy91

cc @ShawnHymel please share on forum as well

**Comment by SwooshMihu** [comment] 2022-08-30 12:37
By using the tutorial here https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/ug_thingy91_gsg.html#id40 regarding how to upload the connectivity bridge firmware on the nRF52840 SOC, i get the following errors: 
![Screenshot from 2022-08-30 15-28-59](https://user-images.githubusercontent.com/47503915/187437072-deff8939-96bb-4f77-aed4-693c75ab25d7.png)
![Screenshot from 2022-08-30 15-28-52](https://user-images.githubusercontent.com/47503915/187437075-48988882-2e25-4aca-9cfd-9e0e1a3acfa5.png)

Thing is, when selecting the device in the Programmer app, both Thingy:91 boards that i have experimented on show up like this 
![Screenshot from 2022-08-30 15-32-27](https://user-images.githubusercontent.com/47503915/187437534-ea9b0c2b-009c-4edc-9ca4-6f9d6dd9ff2a.png)
Any idea why this might be happening?

Worth mentioning is that I encounter no problems flashing the latest Edge Impulse firmware on the nRF9160 SiP.
I am using nrf connect 3.11.1.
Thanks!

**Comment by SwooshMihu** [comment] 2022-08-30 13:03
For another approach, i have used a j-link mini probe to flash the nrf52 with the connectivity bridge using the following command:
```
nrfjprog -f nrf52 --eraseall
nrfjprog -f nrf52 --program ./ei_t91_connectivity_bridge_v1.hex --sectorerase --reset --verify --log 
```
And the nrf91 with the official firmware using:

```
nrfjprog -f nrf91 --eraseall
nrfjprog -f nrf91 --program ./ei_t91_connectivity_bridge_v1.hex --sectorerase --reset --verify --log 
```
The upload was successful in both cases but the timeout issue persists.

**Comment by VojislavM** [comment] 2022-08-30 13:06
@SwooshMihu the second approach is what I was thinking of. 
What is the version of your Thingy91 hardware? 
And did you move the programming switch when selecting the flashing MCU?

**Comment by SwooshMihu** [comment] 2022-08-30 13:10
Yes, i have moved the switch between the respective chip i was programming. 
We have 2 versions of the board, the _1.4.0 2020.23_ and the _1.6.0 2021.09_.

**Comment by mmajchrzycki** [comment] 2022-08-31 09:01
@SwooshMihu, this is wrong:
```
nrfjprog -f nrf91 --program ./ei_t91_connectivity_bridge_v1.hex --sectorerase --reset --verify --log
```
The `connectivity_bridge` firmware is **only** for **nRF52** chip, not nRF91.
So, once again:
1. Download our out-of-the-box firmware:
https://cdn.edgeimpulse.com/firmware/nordic-thingy91.zip
2. Flash `connectivity-bridge.hex` to **nRF52**
3. Flash `firmware.hex` to **nRF91**

If you can't do that using `MCUboot mode`, then probably you've erased the MCUboot. In that situation, use an external probe (like any Nordic DevKit) to flash it using `nrfjprog` or `nRF Connect Programmer`.

**Comment by mmajchrzycki** [comment] 2022-08-31 09:07
After flashing, do a power cycle of the device (disconnect the USB cable, turn off, turn on the device).

**Comment by SwooshMihu** [comment] 2022-08-31 09:08
Sorry, that was a mistake from my side. I have actually flashed the firmware.hex file on the nrf91, not the connectivity bridge. Both flashed using nrfjprog.

**Comment by mmajchrzycki** [comment] 2022-08-31 09:59
@SwooshMihu, I've made additional tests and can confirm that firmware from our CDN is working fine (tested on Thingy91 HW: 1.0.0, flashed using MCUboot mode and also through external probe).
However, the firmware built by our Studio is indeed not working. We are investigating what is wrong and will come back with a fix. But, please reproduce the steps described above to ensure no HW issue.

**Comment by VojislavM** [comment] 2022-08-31 14:55
Just to confirm, there is an issue with firmware running on newer hardware version (1.4.0) and we are looking into it.

**Comment by MukeshSankhla** [comment] 2022-09-01 04:12
> @SwooshMihu, this is wrong:
> 
> ```
> nrfjprog -f nrf91 --program ./ei_t91_connectivity_bridge_v1.hex --sectorerase --reset --verify --log
> ```
> 
> The `connectivity_bridge` firmware is **only** for **nRF52** chip, not nRF91. So, once again:
> 
> 1. Download our out-of-the-box firmware:
>    https://cdn.edgeimpulse.com/firmware/nordic-thingy91.zip
> 2. Flash `connectivity-bridge.hex` to **nRF52**
> 3. Flash `firmware.hex` to **nRF91**
> 
> If you can't do that using `MCUboot mode`, then probably you've erased the MCUboot. In that situation, use an external probe (like any Nordic DevKit) to flash it using `nrfjprog` or `nRF Connect Programmer`.


@mmajchrzycki @VojislavM @ShawnHymel    Thank You, firmware from this link is working.

![Screenshot 2022-09-01 093857](https://user-images.githubusercontent.com/48177784/187829786-ab174351-d3f0-4cde-93ef-d401c4c471ad.png)

**Comment by VojislavM** [comment] 2022-09-01 08:30
@MukeshSankhla great to hear that. Can you please confirm which hardware version of the Thingy 91 you are using? 
It is written here (after you take the orange rubber shield off):
![image](https://user-images.githubusercontent.com/8199477/187869314-317ad1c0-fd04-4e95-8950-4feb82e487ed.png)

**Comment by SwooshMihu** [comment] 2022-09-01 08:50
So i have tried the following, on a **Thingy:91, HW version 1.4.0, using a j-link mini Edu debug probe.**(i had to use a debug probe because this hardware piece does not have MCUboot on it anymore)

1. Downloaded the https://cdn.edgeimpulse.com/firmware/nordic-thingy91.zip firmware
2. Flipped the on-board switch to nRF52 and issued the following command:

```
$nrfjprog -f nrf52 --program ./connectivity-bridge.hex --sectorerase --reset --verify --log 
Parsing image file.
Verifying programming.
Verified OK.
Applying system reset.
Run.
```

2. Flipped the on-board switch to nRF91 and issued the following command:

```
$nrfjprog -f nrf91 --program ./firmware.hex --sectorerase --reset --verify --log 
Parsing image file.
Verifying programming.
Verified OK.
Applying system reset.
Run.
```

3.Power cycled the board and tried to connect it to Edge Impulse ( have also tried it on another linux computer and other USB cable):

```
$edge-impulse-daemon 
Edge Impulse serial daemon v1.15.1
Endpoints:
    Websocket: wss://remote-mgmt.edgeimpulse.com
    API:       https://studio.edgeimpulse.com/v1
    Ingestion: https://ingestion.edgeimpulse.com
```


```
$edge-impulse-data-forwarder
Edge Impulse data forwarder v1.15.1
Endpoints:
    Websocket: wss://remote-mgmt.edgeimpulse.com
    API:       https://studio.edgeimpulse.com/v1
    Ingestion: https://ingestion.edgeimpulse.com

[SER] Could not find any devices connected over serial port
[SER] Retrying in 5 seconds
```


Next up, on **Nordic Thingy:91, HW version 1.6.0 ( which still has MCUboot), using nRF connect v3.11.1 and programmer v3.0.3**, i have succesfully flashed the firmware.hex file from https://cdn.edgeimpulse.com/firmware/nordic-thingy91.zip and succesfully connected it to Edge impulse using _edge-impulse daemon_ and managed to get sensor data from it.

Next up, i have moved on to deploying a model on the edge as a pre-built binary and run it using
$edge-impulse-run-impulse
Edge Impulse impulse runner v1.15.1
? Which device do you want to connect to? /dev/ttyACM0 (Nordic Semiconductor)
[SER] Connecting to /dev/ttyACM0
[SER] Serial is connected, trying to read config...

[SER] Failed to get info off device:undefined. Is this device running a binary built through Edge Impulse? Reconnecting in 5 seconds...

**Comment by VojislavM** [comment] 2022-09-01 09:22
@SwooshMihu Thanks for this feedback! It seems that hardware version 1.4.0 of Thingy91 has a problem with a firmware. 
We are also aware of issue with building firmware with studio and working on resolving this.

**Comment by MukeshSankhla** [comment] 2022-09-01 09:30
> @MukeshSankhla great to hear that. Can you please confirm which hardware version of the Thingy 91 you are using? It is written here (after you take the orange rubber shield off): ![image](https://user-images.githubusercontent.com/8199477/187869314-317ad1c0-fd04-4e95-8950-4feb82e487ed.png)

The Hardware version I have is 1.6.0

Thank you!

**Comment by VojislavM** [comment] 2022-09-01 10:30
@MukeshSankhla Thanks for the info about hardware version. 
@SwooshMihu regarding issue with Thingy91 hardware version 1.4.0. I think this is a modem firmware related issue. What you can do to validate this is to flash the 1.2.3 modem firmware version to your nRF9160 with JLink. 
You can use nRF Connect for Desktop to do that, and download the [1.2.3 modem firmware version from Nordic website](https://www.nordicsemi.com/Products/Development-hardware/Nordic-Thingy-91/Download?lang=en#infotabs)
Let me know if this works for you.

**Comment by VojislavM** [comment] 2022-09-01 13:03
we found the issue, it is currently being resolved and you will be able to use firmware built by the studio on your Thingy91. 
Soon this will be integrated with the EI studio

**Closed as completed** 2022-09-05 10:34 UTC
Labels: bug

**Comment by SwooshMihu** [comment] 2022-09-05 15:08
I have tried deploying the firmware built by the studio on the Nordic Thingy:91 v1.6.0 and i still get the following error:

```
$edge-impulse-run-impulse
Edge Impulse impulse runner v1.15.1
? Which device do you want to connect to? /dev/ttyACM0 (Nordic Semiconductor)
[SER] Connecting to /dev/ttyACM0
[SER] Serial is connected, trying to read config...
[SER] Failed to get info off device:undefined. Is this device running a binary built through Edge Impulse? Reconnecting in 5 seconds...

```
Is there any update regarding the issue?

**Comment by VojislavM** [comment] 2022-09-05 16:15
This is still not added to the production in studio. Will be in next few days. Today public repo for thingy91 (this repo) will be updated and you will be able to use that with generated C++ library from the studio. 

also please check what is the version of the modem firmware you have on your nRF9160 and if needs to be updated as stated in one of the previous posts.

**Comment by mmajchrzycki** [comment] 2022-09-05 18:37
@SwooshMihu, our repository with Thingy91 firmware has been updated. You can find it here: https://github.com/edgeimpulse/firmware-nordic-thingy91
Now you can export the C/C++ library from your project in Studio, put it inside the repository, and build the firmware on your own.

**Comment by SwooshMihu** [comment] 2022-09-08 09:26
Can confirm that now both data forwarder and deployment works. Great work.

One observation that might be worth investigating is that the Gas sensor, part of the Environmental Measurement is constantly 0. I have exposed the sensor to high quantities of CO2, Isopropanol and smoke but the reading is constantly 0 (have tried acquiring data at both 1Hz and 12.5Hz). 

![Screenshot from 2022-09-08 12-18-07](https://user-images.githubusercontent.com/47503915/189086303-1196781f-0342-4f0d-88b6-294c5caac7a2.png)

If needed, i can open a new issue with this. 
Thank you!

**Comment by mmajchrzycki** [comment] 2022-09-08 09:29
@SwooshMihu you can open a new issue, but please check first if the values are zero or near zero (like 0-1).

**Comment by SwooshMihu** [comment] 2022-09-08 09:34
You are totally right, i have verified using the Raw Data processing block and the values are indeed in the vicinity of 1. Thanks!

**Comment by madaerodog** [comment] 2022-09-10 19:02
Thank you guys @mmajchrzycki and @VojislavM both for the continued assistance on the issue!

**Comment by felixphan9** [comment] 2023-09-09 08:39
> @SwooshMihu, this is wrong:
> 
> ```
> nrfjprog -f nrf91 --program ./ei_t91_connectivity_bridge_v1.hex --sectorerase --reset --verify --log
> ```
> 
> The `connectivity_bridge` firmware is **only** for **nRF52** chip, not nRF91. So, once again:
> 
> 1. Download our out-of-the-box firmware:
>    https://cdn.edgeimpulse.com/firmware/nordic-thingy91.zip
> 2. Flash `connectivity-bridge.hex` to **nRF52**
> 3. Flash `firmware.hex` to **nRF91**
> 
> If you can't do that using `MCUboot mode`, then probably you've erased the MCUboot. In that situation, use an external probe (like any Nordic DevKit) to flash it using `nrfjprog` or `nRF Connect Programmer`.

I think the link is broken, can you give me an alternative?

**Comment by mmajchrzycki** [comment] 2023-09-11 08:52
Hi @felixphan9 
Sorry, we moved the firmware to other location. Here is the correct link:
https://cdn.edgeimpulse.com/firmware/thingy91.zip
You can always find all up-to-date links and information [in our docs](https://docs.edgeimpulse.com/docs/development-platforms/officially-supported-mcu-targets/nordic-semi-thingy91).
